# Generated by Django 4.2.5 on 2023-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportGeneration", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="store_id",
            new_name="report_id",
        ),
        migrations.RemoveField(
            model_name="report",
            name="downtime_last_day",
        ),
        migrations.RemoveField(
            model_name="report",
            name="downtime_last_hour",
        ),
        migrations.RemoveField(
            model_name="report",
            name="downtime_last_week",
        ),
        migrations.RemoveField(
            model_name="report",
            name="uptime_last_day",
        ),
        migrations.RemoveField(
            model_name="report",
            name="uptime_last_hour",
        ),
        migrations.RemoveField(
            model_name="report",
            name="uptime_last_week",
        ),
        migrations.AddField(
            model_name="report",
            name="csv_file",
            field=models.FileField(default=1, upload_to="csv_files/"),
            preserve_default=False,
        ),
    ]
