# Generated by Django 4.2.5 on 2023-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportGeneration", "0002_rename_store_id_report_report_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="csv_file",
            field=models.FileField(null=True, upload_to="csv_files/"),
        ),
    ]
