# Generated by Django 4.2.5 on 2023-09-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportGeneration", "0003_alter_report_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
